name: 'actions-akamai-cache-purge'
description: 'cache purge'
author: 'seungjaey'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  CLIENT_TOKEN:
    description: 'akamai auth > client token'
    required: true
  CLIENT_SECRET:
    description: 'akamai auth > client secret'
    required: true
  ACCESS_TOKEN:
    description: 'akamai auth > access token'
    required: true
  HOST:
    description: 'akamai auth > host'
    required: true
  URLS:
    description: 'akamai auth > urls'
    required: true

runs:
  using: node20
  main: dist/index.js
